
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 21 20:39:10 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int LTEQ = 40;
  public static final int EQUALS = 35;
  public static final int GRTEQ = 38;
  public static final int GRT = 37;
  public static final int REM = 31;
  public static final int LPAREN = 13;
  public static final int SEMI = 6;
  public static final int CONTINUE = 20;
  public static final int MINUS = 27;
  public static final int RPAREN = 14;
  public static final int AND = 34;
  public static final int LT = 39;
  public static final int OR = 33;
  public static final int COMMA = 7;
  public static final int CLASS = 11;
  public static final int INC = 24;
  public static final int DIV = 30;
  public static final int PLUS = 28;
  public static final int IF = 16;
  public static final int DOT = 26;
  public static final int FINDANY = 44;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 8;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int NUMBER = 45;
  public static final int IDENT = 46;
  public static final int BREAK = 19;
  public static final int VOID = 15;
  public static final int ARROW = 42;
  public static final int FOREACH = 43;
  public static final int COLON = 41;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int READ = 22;
  public static final int CHARCONST = 48;
  public static final int WHILE = 18;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int MULTI = 29;
  public static final int DEC = 25;
  public static final int PRINT = 23;
  public static final int NOTEQ = 36;
}

